# fly.toml app configuration file generated for bsb-backend on 2025-04-23T14:47:50+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bsb-backend'
primary_region = 'syd'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
